name: "Weather Bot"

on:
  schedule:
    - '0 5 * * *'

jobs:
  bots:
    steps:
      - name: 'Install node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Run code'
        run: node index.js
