name: "Weather Bot"

on:
  schedule:
    - '0 5 * * *'

jobs:
  bot:
    steps:
      - name: 'Install node'
        uses: actions/setup-node@v1
      - name: 'Install NPM dependencies'
        run: npm install
      - name: 'Run code'
        run: node index.js
        env:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
